### ISSUE TITLE
1.19.2 port?

### ISSUE THREAD

**Issue by QianFuv** [Amronos/create-addon-compatibility#10]
Hope it doesn't bother you! Version 1.19.2 isn't outdated, so I think porting is necessary!

**Comment by Amronos** [comment]
I have been thinking about it and it should come soon, whenever I get time to do it.

**Comment by QianFuv** [comment]
Thank you!!!

**Comment by unenlightenment** [comment]
Another thank you!

**Comment by Amronos** [comment]
I'm really sorry, but I don't think I will port the mod to 1.19.2.
I would rather focus on compatibility between more Create addons and port this mod to 1.21 when a Create version for it comes out.
If somebody else wants to make a port, they are free to do so.
