### ISSUE TITLE
Copycat vertical stairs from Copycats+ are uncraftable

### ISSUE THREAD

**Issue by IdeonautMakesGames** [Amronos/create-addon-compatibility#11]
**Describe the bug**
When Create: Addon Compatibility and Create: Copycats+ are installed, Create: Copycats+'s copycat vertical stairs are uncraftable/are hidden in the stone cutter menu.

**Installed Mods**
[Create - 0.5.1.f](https://www.curseforge.com/minecraft/mc-mods/create/files/4835191)
[Create: Copycats+ - 1.3.8](https://www.curseforge.com/minecraft/mc-mods/copycats/files/5481590)
[Create: Addon Compatibility - 0.2.1](https://www.curseforge.com/minecraft/mc-mods/createaddoncompatibility/files/5476164)
[AlmostUnified - 0.9.3](https://www.curseforge.com/minecraft/mc-mods/almost-unified/files/5273070)

**Game Version Information**
Minecraft Version - 1.20.1
Loader - NeoForge 
Loader Version - 47.1.106

**To Reproduce**
1. Install mods listed above
2. In game, open the stone cutter's menu with a zinc ingot in its input

**Expected behavior**
When putting a zinc ingot in the stone cutter's input, you should be able to find and craft copycat vertical stairs.

**Screenshots**

Expected:
![20240704210202_1](https://github.com/Amronos/createaddoncompatibility/assets/91165007/fd6f431f-fae2-4b1d-91fe-746f74910628)

Result:
![20240704210427_1](https://github.com/Amronos/createaddoncompatibility/assets/91165007/37775baf-8c6b-4307-918b-edd518565450)

**Additional context**
I am not sure, but it might also be a bug from AlmostUnified, as having this dependency installed also hides the copycat vertical stairs.

**Comment by Amronos** [comment]
please check if the solution mentioned in #7 fixes it

**Comment by IdeonautMakesGames** [comment]
I have tried installing Create Tab Fix, but it did not fix this problem. I'm sorry as I forgot to mention this in this post, whoops!
