### ISSUE TITLE
cac breaks diesel generators

### ISSUE THREAD

**Issue by CapToad** [Amronos/create-addon-compatibility#15]
**Describe the bug**
when you install cac alongside cdg the engines dont accept some fuels (eg. diesel)

**Installed Mods**
https://modrinth.com/mod/sdaSaQEz AlmostUnified 1.20.1-0.9.4
https://modrinth.com/mod/ZM3tt6p1 Create Diesel Generators 1.20.1-1.2i
https://modrinth.com/mod/QgrK9rtJ Create: Addon Compatibility 0.2.1a
https://modrinth.com/mod/LNytGWDc Create 0.5.1.f

**Game Version Information**
Minecraft Version - 1.20.1
Loader - Forge
Loader Version - 47.3.5

**To Reproduce**
download the mods, (jei too if you want)
either place down one of the engines and pump diesel into it or just check the uses for diesel fluid itself

**Expected behavior**
engines accept diesel (and other fuels)

**Screenshots**
![2024-08-01_18 40 06](https://github.com/user-attachments/assets/64b95d21-fbab-4eda-9c3f-fb9b4607a0b1)

**Comment by CapToad** [comment]
![2024-08-01_18 45 29](https://github.com/user-attachments/assets/81aff765-ace8-43f2-9850-de0b42199058)
and a screenshot to show that the diesel is in the engine and isnt just not getting pumped in

**Comment by CapToad** [comment]
lmao im such a silly goose

**Comment by Amronos** [comment]
I haven't even touched diesel generators or diesel. Do you have any other mods installed? Also make sure that you are pumping fuel into the diesel generator correctly. Also have you tested without cac?

**Comment by CapToad** [comment]
the second screenshot shows that you can pump diesel out of the engine so there is diesel, and  if you replace the diesel with ethanol then it works
after removing ONLY cac (keeping almost unified create and cdg) it suddenly starts working again so yes, its an issue with cac all the mods i have are at the top

**Comment by zeiinsito** [comment]
I have replicated this and it's indeed fixed by removing CAC.

Note that Diesel Generator's fuel tooltips disappear from fuel buckets that won't work while CAC is installed, so maybe this has something to do with how CAC handles fuel tags?
