### ISSUE TITLE
Compatibility with Create: Destroy

### ISSUE THREAD

**Issue by albertosaurio65** [Amronos/create-addon-compatibility#18]
![image](https://github.com/user-attachments/assets/60a6b29c-5d91-43ce-819c-9a90f8100dac)
They are updating the create destroy mod for version 1.0 and I don't know if it will be possible to do something with the snapshots.

**Comment by Penta0308** [comment]
![image](https://github.com/user-attachments/assets/17f57306-6c8d-4cae-bd7b-6e82ee2669cb)

Not fixed.
