### ISSUE TITLE
Datapack fails to load with CaC installed 

### ISSUE THREAD

**Issue by VillainVibe** [Amronos/create-addon-compatibility#5]
I installed the latest update off CaC - createaddoncompatibility-v0.1.2-1.20.1-(neo)forge 
I'm using Neoforged 47.1.104 installed on my server as Loader

Here are the logs 
[latest.log](https://github.com/Amronos/createaddoncompatibility/files/15055275/latest.log)

[crashlog.txt](https://github.com/Amronos/createaddoncompatibility/files/15055277/crashlog.txt)

Regards

**Comment by Amronos** [comment]
You have many mods installed can you try with just cac and the data pack.

**Comment by Amronos** [comment]
You have many mods installed can you try with just cac and the

**Comment by VillainVibe** [comment]
What datapack exactly ? 
Does the log specify what  data pack ? 
I can't seem to find it 
Isn't  CaC a datapack mod ?

**Comment by VillainVibe** [comment]
Isn't CaC the problem here ?
The previous version loaded just fine. 
Only after updating my server failed to load the installed data packs,  I suppose that includes CaC ?

**Comment by VillainVibe** [comment]
I made a testing environment with the following mods and its dependencies installed. 

[Destroy]
(https://modrinth.com/mod/uY7EYHum) [glM7hO6V]
[Ad Astra]
(https://modrinth.com/mod/3ufwT9JF) [WUGYX9Me]
[Create Diesel Generators]
(https://modrinth.com/mod/ZM3tt6p1) [1.20.1-1.2h] by kamień-bot AKA George VI AKA Jesz
[Create: The Factory Must Grow]
(https://modrinth.com/mod/USgVjXsk) [0.8.0b] by DrMangoTea, Pepa, Milky, Luna
[Create]
(https://modrinth.com/mod/LNytGWDc) [HNYrbfZZ]
[Create: Addon Compatibility]
(https://modrinth.com/mod/QgrK9rtJ) [0.1.2] by Amronos
[Create Crafts & Additions]
(https://modrinth.com/mod/kU1G12Nn) [1.20.1-1.2.2 ] by MRH0
[Botarium]
(https://modrinth.com/mod/2u6LRnMa) [2.3.3] by CodexAdrian
[Resourceful Lib]
(https://modrinth.com/mod/G1hIVOrD) [l4YYn2wS]
[Resourceful Config]
(https://modrinth.com/mod/M1953qlQ) [irREd1ZJ]
[Almost Unified]
(https://modrinth.com/mod/sdaSaQEz) [fscv1Pjy]
[Create: Garnished]
(https://modrinth.com/mod/6e2SlzR4) [jRrdlZcx]


Here is the log off the startup of the server that fails to load.
[crash log.txt]
(https://github.com/Amronos/createaddoncompatibility/files/15068482/crash.log.txt)


Hope this helps!

**Comment by Amronos** [comment]
The reason for the crash is the same as https://github.com/Amronos/createaddoncompatibility/issues/2

**Comment by VillainVibe** [comment]
Okay, 
I read the other issue post..
Is there any known fix for the crash ? 
I would like to use the latest update since you added compat for Ad Astra & Create: Garnished.

**Comment by VillainVibe** [comment]
Okay, I see.
So create garnished is acting up if I'm not mistaken if the factory must grow is installed ?

**Comment by Amronos** [comment]
@VillainVibe I have put the reason behind the crash and the solution to it in #2.

**Comment by VillainVibe** [comment]
Thank you
