### ISSUE TITLE
Certain blocks/items not appearing in jei/emi or creative inventory

### ISSUE THREAD

**Issue by ripoy** [Amronos/create-addon-compatibility#7]
copycats+ was updated, and they added new block called copycat vertical stairs. and this block doesnt shows in EMI. i use EMI and JEI
![image](https://github.com/Amronos/createaddoncompatibility/assets/117046926/091e082f-04ad-4a4e-9ccc-a66349624017)

**Comment by Amronos** [comment]
This is a problem which happens sometimes with various blocks or items from create and its addons. This is a bug with create and not related to this mod. Create will update soon with a fix, in the meantime you can use [Create Tab Fix](https://modrinth.com/mod/create-tab-fix), which should fix the issue.
