### ISSUE TITLE
Fuels from Create: Diesel Generators work in Ad Astra's Rockets

### ISSUE THREAD

**Issue by Chris6ix** [Amronos/create-addon-compatibility#9]
**Describe the bug**
The fuels from Create: Diesel Generators (Gasoline, Diesel and BioDiesel) work in Ad Astra's Rockets, which doesn't make any sense since rockets don't work with these "normal" fuels. It would be great if only the "Fuel Bucket" that comes with Ad Astra (Which is basically rocket fuel) would be accepted as fuel in the rockets.

**Installed Mods**
[Ad Astra 1.15.18](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Create 0.5.1f](https://www.curseforge.com/minecraft/mc-mods/create)
[Create: Diesel Generators 1.20.1-1.2i](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
[Create Addon Compatiblity 0.2.0a](https://modrinth.com/mod/createaddoncompatibility)

**Game Version Information**
Minecraft Version - 1.20.1
Loader - Forge
Loader Version - 47.3.1

**To Reproduce**
1. Place a Rocket on a rocket pad
2. Get some diesel
3. Enter the rocket, open the inventory and put the diesel bucket into the fuel slot
4. See that it accepts it as fuel even though it shouldn't

**Expected behavior**
The Rocket should only accept the "Fuel Bucket" that comes with Ad Astra

**Screenshots**
/

**Additional context**
/

**Comment by Amronos** [comment]
Will add a config option for this next update.

**Comment by Chris6ix** [comment]
> Will add a config option for this next update.

Thank you :)

**Comment by Amronos** [comment]
Sadly a config option won't be possible but I will include a datapack in the mod, which will only allow the Ad Astra fuels to be used.
